# Generated by Django 5.2.1 on 2025-05-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mainuser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=35)),
                ('user_mail', models.EmailField(max_length=254, unique=True)),
                ('user_password', models.CharField(max_length=128)),
                ('user_dob', models.DateField()),
                ('user_gender', models.CharField(max_length=10)),
                ('user_phonenumber', models.BigIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gnanow_mainuser',
            },
        ),
    ]
