"""
Django settings for gnanow_project project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from dotenv import load_dotenv
load_dotenv()  # Load from .env file
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-yr(ygunmx&0@426h9%&v1xg##61dgtvn85kq)2dx3e)ss2wmmc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['yashshiva.pythonanywhere.com']


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Add this first
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
     'cloudinary',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'gnanow',
]


DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Cloudinary config


CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET')
}


# MEDIA_URL = '/media/'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gnanow_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gnanow_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'gnanow_db',
        'USER': 'root',
        'PASSWORD': 'root',  # Replace with your MySQL root password
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = '/static/'

# from pathlib import Path
# BASE_DIR = Path(__file__).resolve().parent.parent

# # For local development
# STATICFILES_DIRS = [
#     BASE_DIR / "static",
# ]

# STATIC_ROOT = BASE_DIR / 'staticfiles'


# STATIC_URL = '/static/'
# STATICFILES_DIRS = [BASE_DIR / "static"]

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True #firstly its is true i changed it at payments time
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'teamsmartmart@gmail.com'
EMAIL_HOST_PASSWORD = 'ulbp ryji ygli mqhm'


JAZZMIN_SETTINGS = {
    "site_title": "GNANOW Admin",
    "site_header": "GNANOW Administration",
    "site_brand": "GNANOW",
    "welcome_sign": "Welcome to GNANOW Admin Panel",
    "copyright": "GNANOW",
   
    "site_icon": "images/favicon.ico",      # ✅ favicon
   
    

    # Optional: Dark theme logo
    "welcome_sign": "Login to manage GNANOW store",
    "login_sidebar_background": "images/bg.jpg",  # Optional background image


    "show_sidebar": True,
    "navigation_expanded": True,
    "theme": "flatly",                      # Options: darkly, litera, lux, etc.
}


LOGIN_URL = '/login/'  # Default login page
LOGIN_REDIRECT_URL = '/dashboard/'  # Redirect after login


# SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# SESSION_COOKIE_AGE = 3600
SESSION_ENGINE = "django.contrib.sessions.backends.cache"  # or 'file'



# settings.py
RAZORPAY_ID = 'rzp_test_JtRCVwvuv0LD5v'
RAZORPAY_ACCOUNT_ID = 'itNw7BFj17bBMXv456uI6OlI'


# Secure settings
CSRF_TRUSTED_ORIGINS = ['https://yourusername.pythonanywhere.com']
